### ISSUE TITLE
Integration with next/link

### ISSUE THREAD

**Issue by hobadams** [cyntler/next-locales#34]
Firstly, thanks for creating this solution. It seems to be the best with regards to handling i18n & static html generation.

I'm wondering how you've handled internal linking, specifically using `next/link`.

At the moment all links 404 because they don't contain the locale.

side note - how have you handled translating error pages (404) if they're outside of the `locale` dir?

Thanks for any help.

**Comment by cyntler** [comment]
@hobadams Hey! Try to use <Link /> component from this library. I added the section in readme about it: https://github.com/cyntler/next-locales#support-for-links-with-the-link-component
